# NumPy
* "Fundamental package for scientific computing in Python"
* "At the core of the NumPy package, is the `ndarray` object"
* Provides:
   * multidimensional array object
   * various derived objects:
     * masked arrays
     * matrices
     * ...
   * routines for fast operations on arrays:
     * mathematical
     * logical
     * shape manipulation
     * sorting
     * selecting
     * I/O
     * basic linear algebra
     * basic statistical operations
     * random simulation
     * ...

https://docs.scipy.org/doc/numpy-1.13.0/user/whatisnumpy.html


## `ndarray`
* "Multidimensional container of items of the **same type and size**"
* "Usually fixed-size"
* Shape of the array ("tuple of N positive integers that specify the sizes of each dimension") defines:
  * Number of dimensions
  * Number of items
* `dtype` specifies the data type of the items in the array
* Supports indexing and slicing

https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html

## `ndarray` vs standard Python list

| -                    | `ndarray`       | Python list                       |
|:---------------------|:----------------|:----------------------------------|
| size                 | fixed [1]       | dynamic                           |
| type                 | homogeneous [2] | heterogeneous (Python `object`s)  |
| adv. math operations | available [3]   | write yourself                    |
| implementation       | C array [4]     | list of list(s)                   |


* [1] "Changing the size of an ndarray will create a new array and delete the original."
* [2] All elements will have the **"same size in memory"** (except in case of an array of objects).
* [3] "Typically, such operations are executed **more efficiently** and with less code than is possible using Python’s built-in sequences."
* [4] "NumPy is implemented in C and offers near C-speed"

In addition, many scientific Python packages use and return NumPy arrays.

https://docs.scipy.org/doc/numpy-1.13.0/user/whatisnumpy.html

## NumPy Routines
All functions and methods are documented at https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.html#routines
* [Array creation](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-creation.html)
* [Array manipulation](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-manipulation.html)
* [Data type routines](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.dtype.html)
* [Indexing](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.indexing.html)
* [Linear algebra](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html)
* [Logic functions](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.logic.html)
* [Mathematical functions](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html)
* [The matrix library](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.matlib.html)
* [Random sampling](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.random.html)
* [Sorting, searching, and counting](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.sort.html)
* [Statistics](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.statistics.html)
* [Window functions](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.window.html)
* ...

In [1]:
# usually numpy is imported like this
import numpy as np

## Create NumPy Arrays

"There are 5 general mechanisms for creating arrays:
1. Conversion from other Python structures (e.g., lists, tuples)
2. Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)
3. Reading arrays from disk, either from standard or custom formats
4. Creating arrays from raw bytes through the use of strings or buffers
5. Use of special library functions (e.g., random)"

https://docs.scipy.org/doc/numpy-1.13.0/user/basics.creation.html

See https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-creation.html for an overview of array creation routines. A few important routines are outlined in the following.

### Using the ```array()``` function
```numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)```

"**Parameters:**
* **object:** *array_like*. An array, any object exposing the array interface, an object whose ```__array__``` method returns an array, or any (nested) sequence.
* **dtype:** *data-type, optional*. The desired data-type for the array. If not given, then the type will be determined as the minimum type required to hold the objects in the sequence. This argument can only be used to ‘upcast’ the array. For downcasting, use the ```.astype(t)``` method."
* Check the documentation for the other more advanced parameters.


"**Returns: out:** *ndarray*. An array object satisfying the specified requirements.

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.array.html

The following examples are from the link above.

In [9]:
# create an numpy array from a list
data = [1, 3, 3]
a = np.array(data)
a

array([1, 3, 3])

In [10]:
type(a)

numpy.ndarray

In [11]:
a.dtype

dtype('int64')

In [12]:
# upcast the type from an array from integer to float
# note the dtype of all values in the array
np.array([1, 2, 3.]).dtype

dtype('float64')

In [13]:
# create an array with more than one dimension
np.array( [ [0, 1, 2], [3, 4, 5] ] )

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
np.array([[0, 1, 2], [3, 4, 5]]).shape

(2, 3)

In [15]:
np.array([[0, 1, 2], [3, 4]])

<ipython-input-15-44959dcb9816>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[0, 1, 2], [3, 4]])


array([list([0, 1, 2]), list([3, 4])], dtype=object)

In [17]:
np.array([[0, 1, 2], [3, 4, 5], [3, 4, 5], [3, 4, 5]]).shape

(4, 3)

### Using the ```arange()``` function

```numpy.arange([start, ]stop, [step, ]dtype=None)```

"Return evenly spaced values within a given interval.

Values are generated within the half-open interval ```[start, stop)``` (in other words, the interval including start but excluding stop). For integer arguments the function is equivalent to the Python built-in ```range``` function, but returns an ```ndarray``` rather than a list.

When using a non-integer step, such as ```0.1```, the results will often not be consistent. It is better to use ```linspace``` for these cases."

**Parameters:**
* **start:** *number, optional*. Start of interval. The interval includes this value. The default start value is ```0```.
* **stop:** *number*. End of interval. The interval does not include this value, except in some cases where *step* is not an integer and floating point round-off affects the length of out.
* **step:** *number, optional*. Spacing between values. For any output *out*, this is the distance between two adjacent values, ```out[i+1] - out[i]```. The default step size is ```1```. If *step* is specified, *start* must also be given.
* **dtype:** *dtype*. The type of the output array. If ```dtype``` is not given, infer the data type from the other input arguments.

**Returns: arange:** *ndarray*. Array of evenly spaced values. For floating point arguments, the length of the result is ```ceil((stop - start)/step)```. Because of floating point overflow, this rule may result in the last element of out being greater than *stop*.

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.arange.html

In [19]:
# create an array with stop=3 (and default start and step values)
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [22]:
# create the same array with float data types
np.arange(3.)

array([0., 1., 2.])

In [23]:
# create an array with start=3 and stop=7 (exclusive)
np.arange(3, 7)

array([3, 4, 5, 6])

In [24]:
# create an array with start=3, stop=7 (exclusive), and step=2
np.arange(3, 7, 0.1)

array([3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2,
       4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5,
       5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8,
       6.9])

### Using with or without placeholder values

Some methods for creating NumPy array with or without placeholder values are described in the following.

https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-creation.html#ones-and-zeros

#### ```ones()```
```numpy.ones(shape, dtype=None, order='C')```
"Return a new array of given shape and type, filled with ones.

**Parameters:**
* **shape:** *int or sequence of ints*. Shape of the new array, e.g., ```(2, 3)``` or ```2```.
* **dtype:** *data-type, optional*. The desired data-type for the array, e.g., ```numpy.int8```. Default is ```numpy.float64```.
* **order:** *{‘C’, ‘F’}, optional*. Whether to store multidimensional data in C- or Fortran-contiguous (row- or column-wise) order in memory.

**Returns: out:** *ndarray*. Array of ones with the given shape, dtype, and order."

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ones.html

In [25]:
# create an array of ones with 5 values and the default dtype
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
# create the same array with int as dtype
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

In [34]:
# create and array of ones with two rows and one column
np.ones((3, 3, 3, 5 , 8 , 9))

array([[[[[[1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           ...,
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.]],

          [[1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           ...,
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.]],

          [[1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           ...,
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.]],

          [[1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           ...,
           [1., 1., 1., ..., 1., 1., 1.],
      

In [32]:
np.ones((2))

array([1., 1.])

#### ```zeros()```
```numpy.zeros(shape, dtype=float, order='C')```

"Return a new array of given shape and type, filled with zeros."

Parameters and return value is the same as ```numpy.ones()```.

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.zeros.html

In [35]:
# create an array of zeros with 5 values and the default dtype
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
# create the same array with int as dtype
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [38]:
# create and array of zeros with two rows and one column
np.zeros((2, 1))

array([[0.],
       [0.]])

## ```ndarray``` Attributes

"The most important attributes of an ```ndarray``` object are:"
https://docs.scipy.org/doc/numpy-1.13.0/user/quickstart.html#the-basics

In [39]:
# create a 2d array
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [40]:
# get the type of x
type(x)

numpy.ndarray

In [41]:
# get the shape of the array
x.shape

(2, 3)

In [42]:
# get the data type of the values in the array
x.dtype

dtype('int32')

In [43]:
# get the number of dimensions (axes) in the array
x.ndim

2

In [44]:
# get the total number of elements in the array
x.size

6

In [45]:
# get the size in bytes of each element of the array
x.itemsize

4

In [49]:
x=np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
# indexing (zero-based) for getting a single element of the array
x[:, 2]

array([2, 5, 8])

In [47]:
x[1][2]

6

## Indexing, Slicing, and Iterating

* "**One-dimensional** arrays can be indexed, sliced and iterated over, much like lists and other Python sequences."
* "**Multidimensional** arrays can have one index per axis."
* "The basic **slice syntax** is ```i:j:k``` where *i* is the starting index, *j* is the stopping index, and *k* is the step ($k\neq0$). (...) If *k* is not given it defaults to 1."
* "When fewer indices are provided than the number of axes, the missing indices are considered complete slices ```:```"
* "The expression within brackets in ```b[i]``` is treated as an ```i``` followed by as many instances of ```:``` as needed to represent the remaining axes. NumPy also allows you to write this using dots as ```b[i,...]```."

https://docs.scipy.org/doc/numpy-1.13.0/user/quickstart.html#indexing-slicing-and-iterating and https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#basic-slicing-and-indexing

Examples are based on https://docs.scipy.org/doc/numpy-1.13.0/user/quickstart.html#indexing-slicing-and-iterating.

In [57]:
# creating a 1d array
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
# select a single element
a[3]

3

In [62]:
# slice the array and get elements at index 1 to 5 (exclusive end)
a[3:4]

array([3])

In [63]:
# select all elements starting from index 5
a[5:]

array([5, 6, 7, 8, 9])

In [64]:
# select every second element starting from 1 and stopping at 7 (exclusive)
a[1:7:2]

array([1, 3, 5])

In [65]:
# equivalent to a[0:6:2]
a[:6:2]

array([0, 2, 4])

In [66]:
# reverse the array
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [67]:
#magic indexing
a[[0,5,3]]

array([0, 5, 3])

In [69]:
# iterate the 1d array
for i in a:
    print(i*2, end = " ")

2*a

0 2 4 6 8 10 12 14 16 18 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [70]:
# create a 2d array
def f(x, y):
    return 10*x+y

b = np.fromfunction(f, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [71]:
b[3, :]

array([30, 31, 32, 33])

In [72]:
# indexing (zero-based) for getting a single element of the array
b[2, 3]

23

In [73]:
# get all elements of the second column
b[:, 1]

array([ 1, 11, 21, 31, 41])

In [75]:
# get all columns of the 2nd and 3rd row
b[1:3, 1:3]

array([[11, 12],
       [21, 22]])

In [76]:
# get the last row of the array
b[-1]

array([40, 41, 42, 43])

In [77]:
# iterate over 2d array
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [78]:
rows = [0,3]
col=[0,3]
b[rows,col]

array([ 0, 33])

In [79]:
# iterate over flattened 2d array
for element in b.flat:
    print(element , end = " ")

0 1 2 3 10 11 12 13 20 21 22 23 30 31 32 33 40 41 42 43 

In [81]:
b.flat

## Shape Manipulation
An introduction to the manipulation of the shape of arrays is provided at https://docs.scipy.org/doc/numpy-1.13.0/user/quickstart.html#shape-manipulation

### Change the shape
* [```reshape()```](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.reshape.html) "gives a new shape to an array without changing its data. returns a copy"
* [```flatten()```](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.flatten.html) returns "a copy of the array collapsed into one dimension."
* [```T```](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html) transposes the array.

```reshape()```, ```flatten()```, and ```T``` "return a new modified array (but do not change the original array")

In [82]:
a = np.arange(10)

In [83]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
a.shape

(10,)

In [88]:
# reshape the array into 5 rows and 2 columns
c = a.reshape((5, 2))
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [89]:
a.reshape((2, -1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [90]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [92]:
# flatten the array (a copy will be returned)
b.flatten()

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [94]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [95]:
b.shape

(5, 4)

In [96]:
# change the shape of the original array
b.reshape((2, 10))


array([[ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21],
       [22, 23, 30, 31, 32, 33, 40, 41, 42, 43]])

In [98]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [99]:
b.shape

(5, 4)

In [97]:
# return the array transposed
b.T

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43]])

In [100]:
b.T.shape

(4, 5)

In [101]:
b.transpose()

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43]])

### Stacking
"Several arrays can be stacked together along different axes." (https://docs.scipy.org/doc/numpy-1.13.0/user/quickstart.html#stacking-together-different-arrays). The methods ```hstack```, ```vstack```, ```row_stack```, and ```column_stack``` are still supported but ```stack``` or ```concatenate``` should be used for joining arrays.



* [```stack(arrays, axis=0)```](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.stack.html) joins "a sequence of arrays along a new axis."
* [```concatenate(arrays, axis=0)```](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.concatenate.html) joins "a sequence of arrays along an existing axis."

In [ ]:
# create 3 numpy arrays
a = np.array((1, 2, 3))
b = np.array((4, 5, 6))
c = np.array((7, 8, 9))

In [ ]:
b

In [ ]:
# stack arrays along the first axis (row wise)
np.stack((a, b, c))

In [ ]:
np.stack((a, b, c)).shape

In [ ]:
# stack arrays along the last axis (column wise)
np.stack((a, b, c), axis=1)

In [ ]:
# concatenate the arrays
np.concatenate((a, b, c))

In [ ]:
# stack arrays a, b, and c to create a 3x3 matrix
abc = np.stack((a, b, c))
abc

In [ ]:
abc.shape

In [ ]:
# create a new array d
d = np.array([[10, 11, 12]])
d

In [ ]:
d.shape

In [ ]:
# concat abc and d along axis 0 (row-wise)
np.concatenate((abc, d), axis=0)

In [ ]:
# concat abc and d along axis 1 (column-wise)
np.concatenate((abc, d.T), axis=1)

## Lists vs NumPy array

In [ ]:
# speed comparison for 2D arrays

# for loop with lists
def for_loop(dim):
    n = []
    # first dimension
    for i in range(dim):
        n.append([])
        # second dimension
        for j in range(dim):
            n[i].append(j)
    return n

# list comprehension
def list_comp(dim):
    # double list comprehension
    n = [[j for j in range(dim)] for i in range(dim)]
    return n

# numpy array
def numpy_array(dim):
    return np.array([np.arange(dim, dtype=np.int32) for i in range(dim)])

In [ ]:
for_loop(5)

In [ ]:
list_comp(5)

In [ ]:
numpy_array(5)

In [ ]:
dim = 100

%timeit for_loop(dim)
%timeit list_comp(dim)
%timeit numpy_array(dim)

# NumPy Summary
* ``ndarray``: fast, fixed-size and same type, memory efficient array with advanced build-in mathematical operations
* Basis for many (all?) popular ML libraries
* Use ``ndarray`` (and learn how to use it correctly)! Read the documentation at https://docs.scipy.org/doc/numpy-1.13.0/index.html

# NumPy Exercises


In [ ]:
import numpy as np

In [ ]:
np.random.seed = 42
a = np.random.rand(10,10,)

- Select the first column from `a`
- Select the first fifth and sixth row from `a`
- Select the first element of the second row


In [ ]:
b = a = np.random.rand(10,3,3)

- What is `b` shape?
- Make `b` 2D with a shape of 10,9

- Erstelle eine 5x5-Matrix mit 7er auf der Diagonalen
- Erstelle eine 7x7-Matrix mit Nullen am Rand und Einsen in der Mitte
- Berechne die Lösung des Gleichungssystems:
    
  \begin{gather}
\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} 
\begin{bmatrix}
x_1 \\ x_2
\end{bmatrix}
         =
          \begin{bmatrix}
           2 \\
          5 
           \end{bmatrix}
        \end{gather}
    Hinweis: Verwende np.linalg.inv() um die Inverse der Matrix zu berechnen.
    
 
 

$ x_1 + 2* x_2 = 2$

$ 3*x_1 + 4* x_2 = 5$

In [109]:
A = np.arange(1,5).reshape((2,2))
b = np.array([2, 5])

inv_A = np.linalg.inv(A)
inv_A

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [110]:
inv_A@b

array([1. , 0.5])

In [113]:
5*np.arange(7)+1 > 5

array([False,  True,  True,  True,  True,  True,  True])

In [102]:
7 * np.eye(7)

array([[7., 0., 0., 0., 0., 0., 0.],
       [0., 7., 0., 0., 0., 0., 0.],
       [0., 0., 7., 0., 0., 0., 0.],
       [0., 0., 0., 7., 0., 0., 0.],
       [0., 0., 0., 0., 7., 0., 0.],
       [0., 0., 0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 0., 0., 7.]])

In [105]:
a = np.zeros((7,7))
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [107]:
for i in range(7):
    a[i, i] = 7
    
a

array([[7., 0., 0., 0., 0., 0., 0.],
       [0., 7., 0., 0., 0., 0., 0.],
       [0., 0., 7., 0., 0., 0., 0.],
       [0., 0., 0., 7., 0., 0., 0.],
       [0., 0., 0., 0., 7., 0., 0.],
       [0., 0., 0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 0., 0., 7.]])